### ISSUE TITLE
选中翻译和划词翻译都不支持Frame

### ISSUE THREAD

**Issue by arloan** [DhyanaChina/touch-dog#11]
Type:
- [√ ] Bug
- [ ] Feature
- [ ] Help   

Version:   
0.2.0

Description:  
在 frame 内容里选中翻译和划词翻译都不出现翻译窗口。例如 QQMail 邮件查看。

**Comment by WittBulter** [comment]
已修复，注意更新版本。

**Comment by arloan** [comment]
Confirmed. Good job!
