### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by madisman** [DhyanaChina/touch-dog#16]
Type:
- [ ] Bug
- [ ] Feature
- [ ] Help   

Version:   

Description:  不能够翻译是怎么回事

**Comment by zqjilove** [comment]
搭车反馈问题：360极速浏览器，安装插件，不能翻译！

**Comment by WittBulter** [comment]
@madisman 
API 出了点问题，更新版本解决。
后面会再升级一波，优化一下翻译结果。

@zqjilove 只支持 Chrome
