### ISSUE TITLE
历史记录

### ISSUE THREAD

**Issue by kosmgco** [DhyanaChina/touch-dog#18]
Type:
- [ ] Bug
- [x] Feature
- [ ] Help   

Version:   

Description:  
可以增加历史记录吗？过一段时间再回顾之前用到翻译的单词

**Comment by WittBulter** [comment]
可以。主要的问题是划词翻译非常长的句子后展示历史纪录对排版有些影响。
增加历史纪录的排版需要重构点击图标弹出的控制面板，可以加在下次迭代里。

另外正好调查一下，如果需要注册 (仅跳转邮箱注册验证，增加用户名)，会影响使用的体验吗？
这里是因为目前的翻译 API 不够精确，准备换成更专业的翻译 API，但为防止个别用户过度使用或验证信息，紧急停用部分用户等功能需要增加用户邮箱验证的步骤，对你来说，会阻碍你继续使用吗，或者大家有没有更好的想法？(都可以回复这个 issue)

**Comment by kosmgco** [comment]
长句就不加到历史记录里面吧

我觉得加一个认证也没关系，对我来说影响不大
